name: cloud-provider-openstack
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

secret:
  create: true

cloudConfig:
  global:
    auth-url:
    username:
    password:
    tenant-id:
    domain-name:
    region:
  networking:
    ipv6-support-disabled: true
    public-network-name:
  loadBalancer:
    internal-lb: false
    floating-network-id:
    create-monitor: true
    # network-id:
    # subnet-id:
  # blockStorage:
  # metadata:

openstack-cinder-csi:
  clusterID: {}
  csi:
    snapshotController:
      enabled: true
    plugin:
      image:
        repository: docker.io/k8scloudprovider/cinder-csi-plugin
        pullPolicy: IfNotPresent
        tag:  # defaults to .Chart.AppVersion
      volumes:
        - name: cacert
          hostPath:
            path: /etc/cacert
      volumeMounts:
        - name: cacert
          mountPath: /etc/cacert
          readOnly: true
        - name: cloud-config
          mountPath: /etc/kubernetes/
          readOnly: true
  secret:
    enabled: true
    create: false
    name: cloud-config
  storageClass:
    enabled: true
    delete:
      isDefault: true
      allowVolumeExpansion: true
    retain:
      isDefault: false
      allowVolumeExpansion: true
    custom: |-
      ---
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshotClass
      metadata:
        name: csi-cinder-snapclass
      driver: cinder.csi.openstack.org
        deletionPolicy: Delete
openstack-cloud-controller-manager:
  image:
    repository: docker.io/k8scloudprovider/openstack-cloud-controller-manager
    tag: "v1.23.1"
  # Create a service monitor for Prometheus Operator
  # serviceMonitor:
  #  enabled: true
  controllerExtraArgs: {}
  secret:
    create: false
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/controlplane
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    value: "true"
    effect: NoExecute
